dev:
  bk:
    url: "https://qa-bk.cubivue.com/"
    user: 'hs'
    pwd: '1234'
    login_api: "https://qa-bk-api.cubivue.com/api/Account/Login"
  ekl:
    url:
    user:
    pwd:
  kinnarps:
    url: "https://tpdev.kinnarps.com/"
    base_url: "https://tpdev-api.kinnarps.com"
    user: Wahab
    pwd: qwe123

Qa:
  bk:
    url: "https://qa-bk.cubivue.com/"
    user: 'hs'
    pwd: '1234'
    login_api: "https://qa-bk-api.cubivue.com/api/Account/Login"
  ekl:
    url:
    user:
    pwd:
  kinnarps:
    url: "https://tptest.kinnarps.com/"
    base_url: "https://tptest-api.kinnarps.com"
    user: Wahab
    pwd: qwe123
prod:
  bk:
    url: "https://qa-bk.cubivue.com/"
    user: 'hs'
    pwd: '1234'
    login_api: "https://qa-bk-api.cubivue.com/api/Account/Login"
  ekl:
    url:
    user:
    pwd:
  kinnarps:
    url: "https://tptest.kinnarps.com/"
    base_url: "https://tptest-api.kinnarps.com"
    user: Wahab
    pwd: qwe123
execution:
  current_exec: dev
  current_module: kinnarps
  browser: chromium
  screen_shot: False
  headless: False
